New dash (#2)
* More portfolio utils

* portfolio overview

* websockets

* new dash

* merge

* Fix missing cache methods in KalshiAPIClient

- Added missing _get_cached, _set_cache, _get_cache_key, _is_cache_valid methods
- Added clear_cache and get_cache_stats methods
- Fixes AttributeError: 'KalshiAPIClient' object has no attribute '_get_cached'

* bugfixes

* new dash

* refactor

* unrealized PnL

* unrealized pnl dashboard